spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
server:
  max-http-request-header-size: 16KB
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Ensure full sampling if desired
  endpoints:
    web:
      exposure:
        include: "info,health"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
otel:
  traces:
    exporter:
      otlp:
        endpoint: "http://localhost:4317"  # Change this to your OTLP endpoint
  metrics:
    exporter:
      otlp:
        endpoint: "http://localhost:4318"  # Change this to your OTLP endpoint
  logs:
    exporter:
      console:
        enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name:}]"
  level:
    io.opentelemetry: INFO