spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
server:
  max-http-request-header-size: 16KB
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Ensure full sampling if desired
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
otel:
  traces:
    exporter: jaeger
    service:
      name: audition-api
    jaeger:
      endpoint: http://localhost:14250


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    io.opentelemetry: INFO